package channel

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"
)

// ErrInvalidSessionIdentity identifies a routing identity that cannot be
// safely associated with a Session. It is intentionally stable so callers can
// classify malformed or tampered queue payloads without exposing identifiers.
var ErrInvalidSessionIdentity = errors.New("session identity is invalid")

// SessionIdentity separates the human actor from the durable session owner.
// For direct messages both values are the user. For group messages the owner
// is a deterministic opaque key shared by all members of that conversation.
type SessionIdentity struct {
	SessionID      string
	SessionOwnerID string
	ActorUserID    string
}

// BuildSessionIdentity derives the canonical session and owner at trusted
// ingress. The caller should overwrite any adapter-provided SessionOwnerID.
func BuildSessionIdentity(msg *InboundMessage) (SessionIdentity, error) {
	if msg == nil || !validSessionComponent(msg.ExternalUserID) {
		return SessionIdentity{}, ErrInvalidSessionIdentity
	}
	sessionID := generateSessionID(msg)
	if sessionID == "" {
		return SessionIdentity{}, ErrInvalidSessionIdentity
	}
	ownerID, err := SessionOwnerIDFor(msg, sessionID)
	if err != nil {
		return SessionIdentity{}, err
	}
	return SessionIdentity{
		SessionID:      sessionID,
		SessionOwnerID: ownerID,
		ActorUserID:    msg.ExternalUserID,
	}, nil
}

// SessionOwnerIDFor derives the Runner user key for an already selected
// session. Callers at a trusted boundary must validate the session ID with
// ValidateSessionIdentity first. Keeping derivation separate also lets an
// operator explicitly replay a legacy record without making arbitrary IDs
// valid for newly accepted traffic.
func SessionOwnerIDFor(msg *InboundMessage, sessionID string) (string, error) {
	if msg == nil || !validSessionComponent(msg.ExternalUserID) ||
		!validSessionComponent(sessionID) {
		return "", ErrInvalidSessionIdentity
	}
	if !msg.IsGroupChat {
		return msg.ExternalUserID, nil
	}
	if !validSessionComponent(msg.ConversationID) {
		return "", ErrInvalidSessionIdentity
	}
	digest := sha256.Sum256([]byte("group-owner\x00" + sessionID))
	return "group_" + hex.EncodeToString(digest[:]), nil
}

// ValidateCanonicalSessionIdentity checks a queue payload against trusted
// durable routing fields. The session ID must be the canonical ID derived from
// the tenant/channel/account/conversation tuple. This check is intentionally
// strict: accepting a durable ID supplied by a caller lets a corrupted queue
// row bind one conversation to another conversation's Session.
func ValidateCanonicalSessionIdentity(msg *InboundMessage, expectedSessionID, expectedOwnerID string) error {
	if msg == nil {
		return ErrInvalidSessionIdentity
	}
	identity, err := BuildSessionIdentity(msg)
	if err != nil {
		return err
	}
	if expectedSessionID != identity.SessionID {
		return fmt.Errorf("%w: session ID does not match canonical conversation", ErrInvalidSessionIdentity)
	}
	if expectedOwnerID != "" && identity.SessionOwnerID != expectedOwnerID {
		return fmt.Errorf("%w: session owner mismatch", ErrInvalidSessionIdentity)
	}
	return nil
}

// ValidateSessionIdentity checks a queue payload against trusted durable
// routing fields. It retains compatibility with pre-canonical durable rows;
// new ingress and canonical `sess_` rows must use
// ValidateCanonicalSessionIdentity instead.
func ValidateSessionIdentity(msg *InboundMessage, expectedSessionID, expectedOwnerID string) error {
	if msg == nil {
		return ErrInvalidSessionIdentity
	}
	if strings.HasPrefix(expectedSessionID, "sess_") {
		return ValidateCanonicalSessionIdentity(msg, expectedSessionID, expectedOwnerID)
	}
	ownerID, err := SessionOwnerIDFor(msg, expectedSessionID)
	if err != nil {
		return err
	}
	if expectedOwnerID != "" && ownerID != expectedOwnerID {
		return fmt.Errorf("%w: session owner mismatch", ErrInvalidSessionIdentity)
	}
	return nil
}

// NormalizeSessionOwner fills a missing owner and rejects a caller-provided
// owner that does not match the actor/session relationship. This is used at
// the Worker boundary, where direct in-process callers may use legacy session
// IDs that were not generated by an IM adapter.
func NormalizeSessionOwner(msg *InboundMessage, sessionID string) (string, error) {
	owner, err := SessionOwnerIDFor(msg, sessionID)
	if err != nil {
		return "", err
	}
	if strings.TrimSpace(owner) == "" {
		return "", ErrInvalidSessionIdentity
	}
	return owner, nil
}
