package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/google/uuid"
	"trpc.group/trpc-go/trpc-agent-go/enterprise/pkg/datamigration"
	"trpc.group/trpc-go/trpc-agent-go/enterprise/pkg/telemetry"
)

type commandOptions struct {
	action, id, tenantID, source, target, sourceBackend, targetBackend string
	domain                                                             datamigration.Domain
	actor, reason, owner                                               string
	configVersion                                                      int64
	batchSize                                                          int
	interval, timeout, lease                                           time.Duration
}

func parseCommand(args []string, output io.Writer) (commandOptions, error) {
	var options commandOptions
	if len(args) == 0 {
		return options, errors.New("use create, status, step, run, pause, resume, complete, rollback, or abort")
	}
	options.action = args[0]
	switch options.action {
	case "create", "status", "step", "run", "pause", "resume", "complete", "rollback", "abort":
	default:
		return options, errors.New("unknown data migration command")
	}
	flags := flag.NewFlagSet("data-migrate "+options.action, flag.ContinueOnError)
	flags.SetOutput(output)
	flags.StringVar(&options.id, "id", "", "durable migration ID")
	flags.StringVar(&options.tenantID, "tenant", "", "tenant ID (create)")
	domain := flags.String("domain", "", "session, knowledge, or artifact (create)")
	flags.StringVar(&options.source, "source-profile", "", "current operator-owned profile (create)")
	flags.StringVar(&options.target, "target-profile", "", "destination operator-owned profile (create)")
	flags.StringVar(&options.sourceBackend, "source-backend", "", "current backend type (create)")
	flags.StringVar(&options.targetBackend, "target-backend", "", "destination backend type (create)")
	flags.Int64Var(&options.configVersion, "config-version", 0, "expected tenant config_version (create)")
	flags.StringVar(&options.actor, "actor", "", "operator identity for an audited action")
	flags.StringVar(&options.reason, "reason", "", "reason for an audited action")
	flags.StringVar(&options.owner, "owner", "", "unique process lease owner; generated by default")
	flags.IntVar(&options.batchSize, "batch-size", 100, "maximum records per copy batch")
	flags.DurationVar(&options.interval, "interval", time.Second, "delay between bounded steps (run)")
	flags.DurationVar(&options.timeout, "timeout", 30*time.Minute, "total command deadline")
	flags.DurationVar(&options.lease, "lease", 2*time.Minute, "renewable migration lease duration")
	if err := flags.Parse(args[1:]); err != nil {
		return options, err
	}
	if len(flags.Args()) != 0 {
		return options, errors.New("unexpected positional arguments")
	}
	if !validOperatorText(options.id, 128) {
		return options, errors.New("--id must be a nonempty, control-free migration ID")
	}
	if options.batchSize < 1 || options.batchSize > 1000 || options.interval <= 0 || options.timeout <= 0 || options.lease < time.Second || options.lease > 24*time.Hour {
		return options, errors.New("invalid batch size, interval, timeout, or lease")
	}
	if options.owner == "" {
		options.owner = "data-migrate-" + uuid.NewString()
	} else if !validOperatorText(options.owner, 128) {
		return options, errors.New("invalid lease owner")
	}
	options.domain = datamigration.Domain(*domain)
	if options.action == "create" {
		if options.domain != datamigration.DomainSession && options.domain != datamigration.DomainKnowledge && options.domain != datamigration.DomainArtifact {
			return options, errors.New("--domain must be session, knowledge, or artifact")
		}
		if options.configVersion < 1 || !validOperatorText(options.tenantID, 128) || !validOperatorText(options.source, 128) || !validOperatorText(options.target, 128) || options.source == options.target {
			return options, errors.New("create requires tenant, distinct source/target profiles, and a positive config-version")
		}
		if !validBackendPair(options.domain, options.sourceBackend, options.targetBackend) {
			return options, errors.New("unsupported source/target backend pair")
		}
	}
	if options.action == "create" || options.action == "pause" || options.action == "resume" || options.action == "complete" || options.action == "rollback" || options.action == "abort" {
		if !validOperatorText(options.actor, 128) || !validOperatorText(options.reason, 1024) {
			return options, errors.New("audited actions require nonempty, control-free --actor and --reason")
		}
	}
	return options, nil
}

func validOperatorText(value string, limit int) bool {
	return strings.TrimSpace(value) != "" && len(value) <= limit && !strings.ContainsAny(value, "\x00\r\n\t")
}

func validBackendPair(domain datamigration.Domain, source, target string) bool {
	switch domain {
	case datamigration.DomainSession:
		return (source == "redis" || source == "postgres") && (target == "redis" || target == "postgres")
	case datamigration.DomainKnowledge:
		return source == "qdrant" && target == "qdrant"
	case datamigration.DomainArtifact:
		return source == "s3" && target == "s3"
	default:
		return false
	}
}

type migrationController interface {
	Create(context.Context, datamigration.LiveRequest) (datamigration.Job, error)
	Get(context.Context, string) (datamigration.Job, error)
	RunOnce(context.Context, string) (datamigration.Job, error)
	Pause(context.Context, string, string, string) (datamigration.Job, error)
	Resume(context.Context, string, string, string) (datamigration.Job, error)
	Complete(context.Context, string, string, string) (datamigration.Job, error)
	Rollback(context.Context, string, string, string) (datamigration.Job, error)
	Abort(context.Context, string, string, string) (datamigration.Job, error)
}

func execute(ctx context.Context, controller migrationController, options commandOptions, output io.Writer) error {
	var job datamigration.Job
	var err error
	switch options.action {
	case "create":
		job, err = controller.Create(ctx, datamigration.LiveRequest{
			ID: options.id, TenantID: options.tenantID, Domain: options.domain,
			SourceProfile: options.source, TargetProfile: options.target,
			SourceBackend: options.sourceBackend, TargetBackend: options.targetBackend,
			ExpectedConfigVersion: options.configVersion, Actor: options.actor, Reason: options.reason,
		})
	case "status":
		job, err = controller.Get(ctx, options.id)
	case "step":
		job, err = controller.RunOnce(ctx, options.id)
	case "pause":
		job, err = controller.Pause(ctx, options.id, options.actor, options.reason)
	case "resume":
		job, err = controller.Resume(ctx, options.id, options.actor, options.reason)
	case "complete":
		job, err = controller.Complete(ctx, options.id, options.actor, options.reason)
	case "rollback":
		job, err = controller.Rollback(ctx, options.id, options.actor, options.reason)
	case "abort":
		job, err = controller.Abort(ctx, options.id, options.actor, options.reason)
	case "run":
		return runSteps(ctx, controller, options, output)
	default:
		return errors.New("unknown data migration command")
	}
	if err != nil {
		return err
	}
	return json.NewEncoder(output).Encode(job)
}

func runSteps(ctx context.Context, controller migrationController, options commandOptions, output io.Writer) error {
	encoder := json.NewEncoder(output)
	for {
		job, err := controller.Get(ctx, options.id)
		if err != nil {
			return err
		}
		if job.Paused || job.Phase == datamigration.PhaseRollbackWindow || job.Phase == datamigration.PhaseComplete || job.Phase == datamigration.PhaseRolledBack {
			return encoder.Encode(job)
		}
		job, err = controller.RunOnce(ctx, options.id)
		if err != nil && !errors.Is(err, datamigration.ErrMigrationLeaseHeld) {
			return err
		}
		if err == nil {
			if err := encoder.Encode(job); err != nil {
				return err
			}
		}
		timer := time.NewTimer(options.interval)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
	}
}

func main() {
	options, err := parseCommand(os.Args[1:], os.Stderr)
	if errors.Is(err, flag.ErrHelp) {
		return
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	rootCtx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	ctx, cancel := context.WithTimeout(rootCtx, options.timeout)
	defer cancel()
	err = runCommand(ctx, options, os.Stdout)
	if err != nil {
		fmt.Fprintf(os.Stderr, "data migration command failed: error=%s\n", telemetry.StableErrorCode(err))
		os.Exit(1)
	}
}
