[CmdletBinding()]
param(
    [ValidatePattern('^[a-z0-9][a-z0-9_-]{0,62}$')]
    [string]$ProjectName = 'trpc-console-lab',
    [ValidateRange(1024,65535)][int]$AdminPort = 38081,
    [ValidateRange(1024,65535)][int]$GatewayPort = 38080,
    [ValidateRange(1024,65535)][int]$PostgresPort = 45432,
    [ValidateRange(1024,65535)][int]$PrometheusPort = 39095,
    [ValidateRange(1024,65535)][int]$GrafanaPort = 33000,
    [ValidateRange(1024,65535)][int]$OtelGrpcPort = 44317,
    [ValidateRange(1024,65535)][int]$OtelHttpPort = 44318,
    [switch]$Build,
    [switch]$SeedExamples,
    [switch]$Down
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ports = @($AdminPort,$GatewayPort,$PostgresPort,$PrometheusPort,$GrafanaPort,$OtelGrpcPort,$OtelHttpPort)
if (@($ports | Select-Object -Unique).Count -ne $ports.Count) { throw 'Each published service needs a distinct port.' }

$stackArgs = @{
    ProjectName=$ProjectName; AdminPort=$AdminPort; GatewayPort=$GatewayPort
    PostgresPort=$PostgresPort; PrometheusPort=$PrometheusPort; GrafanaPort=$GrafanaPort
    OtelGrpcPort=$OtelGrpcPort; OtelHttpPort=$OtelHttpPort; Build=$Build; Down=$Down
}
& (Join-Path $PSScriptRoot 'run_c_local_stack.ps1') @stackArgs
if ($Down) { return }

$base = "http://127.0.0.1:$AdminPort"
$headers = @{ Authorization='Bearer validation-only-admin-token-32-bytes' }
$ready = $false
for ($attempt=0; $attempt -lt 60; $attempt++) {
    try {
        $response = Invoke-WebRequest "$base/health" -UseBasicParsing -TimeoutSec 3
        if ([int]$response.StatusCode -eq 200) { $ready=$true; break }
    } catch { }
    Start-Sleep -Seconds 1
}
if (-not $ready) { throw 'Admin did not become ready; inspect this Compose project logs.' }
$identity = Invoke-RestMethod "$base/api/v1/operations/me" -Headers $headers -TimeoutSec 10
if ($identity.role -ne 'platform_admin') { throw 'Console lab principal is not available.' }
$page = Invoke-WebRequest "$base/console/" -UseBasicParsing -TimeoutSec 10
if ([int]$page.StatusCode -ne 200 -or $page.Headers['Content-Type'] -notmatch 'text/html') { throw 'Console assets are unavailable.' }

function Invoke-LabWrite([string]$Path, [object]$Body) {
    $json = $Body | ConvertTo-Json -Depth 20 -Compress
    Invoke-RestMethod "$base$Path" -Method Post -Headers $headers -ContentType 'application/json; charset=utf-8' -Body ([Text.Encoding]::UTF8.GetBytes($json)) -TimeoutSec 20
}

if ($SeedExamples) {
    # These are real persisted configuration records. No IM callback, model
    # request, or synthetic execution record is generated by this setup.
    $suffix = [Guid]::NewGuid().ToString('N').Substring(0,8)
    foreach ($entry in @(
        @{name='零售支持'; session='redis'; memory='postgres'},
        @{name='企业知识服务'; session='postgres'; memory='redis'}
    )) {
        $config = @{
            agents=@(@{name='support';type='llm';defaultModel='gpt-4o-mini';maxLLMCalls=4;tools=@()})
            models=@(@{provider='openai';modelName='gpt-4o-mini';apiKey='local-console-example-replace-before-use';maxTokens=1024})
            toolPolicy=@{mode='whitelist';allowed=@()}; channels=@()
            storage=@{sessionBackend=$entry.session;sessionProfile="local-$($entry.session)";memoryBackend=$entry.memory;memoryProfile="local-$($entry.memory)"}
            governance=@{auditLevel='detailed'}
            budget=@{maxTokensPerDay=1000000;maxTokensPerRequest=512000;maxConcurrentSessions=4}
        }
        $tenant = Invoke-LabWrite '/api/v1/tenants' @{name="$($entry.name) · 本地示例 $suffix";config=$config}
        $tenantId = [string]$tenant.id
        if ([string]::IsNullOrWhiteSpace($tenantId)) { throw 'Tenant creation did not return an ID.' }
        Invoke-LabWrite '/api/v1/agent-apps' @{tenantId=$tenantId;name='support';description='租户级数据后端组合示例'} | Out-Null
        $versions = @()
        foreach ($prompt in @('简洁回答客户问题。','先确认需求，再给出可执行步骤。')) {
            $snapshot = @{agent=@{name='support';type='llm';defaultModel='gpt-4o-mini';systemPrompt=$prompt;maxLLMCalls=4;tools=@()};model=@{provider='openai';modelName='gpt-4o-mini';maxTokens=1024}}
            $version = Invoke-LabWrite '/api/v1/agent-versions' @{tenantId=$tenantId;appName='support';snapshot=$snapshot}
            Invoke-LabWrite "/api/v1/agent-versions/$($version.id)/publish" @{tenantId=$tenantId} | Out-Null
            $versions += [string]$version.id
        }
        Invoke-LabWrite '/api/v1/deployments' @{tenantId=$tenantId;appName='support';stableVersionId=$versions[0];canaryVersionId=$versions[1];canaryBps=1000} | Out-Null
        Write-Output "Example ready: tenant=$tenantId Session=$($entry.session) Memory=$($entry.memory) canary=10%"
    }
}

Write-Output "Console: $base/console/"
Write-Output 'Local login token: validation-only-admin-token-32-bytes'
Write-Output "Prometheus: http://127.0.0.1:$PrometheusPort"
Write-Output 'Example model credentials must be replaced before connecting an actual model or IM account.'
