#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

if [[ "$ENV_FILE" == ".env" ]]; then
  ENV_FILE="deploy/.env.wecom.local"
fi
umask 077
mkdir -p "$(dirname "$ENV_FILE")"

fail() {
  printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

require_match() {
  local value="$1" pattern="$2" description="$3"
  [[ "$value" =~ $pattern ]] || fail "$description"
}

random_urlsafe() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -d '\r\n=+/' | cut -c1-48
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c 'import secrets; print(secrets.token_urlsafe(36)[:48])'
  else
    fail "openssl or python3 is required to generate local secrets"
  fi
}

ensure_secret() {
  local key="$1" current
  current=$(_existing "$key" || true)
  if [[ -z "$current" ]]; then
    current=$(random_urlsafe)
  fi
  printf -v "$key" '%s' "$current"
}

banner "WeCom sandbox setup"

stage "Enterprise and self-built app"
say "Use a dedicated test enterprise and a self-built application, not a production app."
open_url "https://work.weixin.qq.com/wework_admin/frame"
step "Scan the QR code with an enterprise administrator account."
step "Open My Enterprise and copy the Corp ID."
ask WECOM_CORP_ID "Corp ID (ww + 16 lowercase hex characters):"
require_match "$WECOM_CORP_ID" '^ww[0-9a-f]{16}$' "Corp ID has an invalid shape"
step "Open App Management, select or create the test self-built app, then copy AgentId."
ask WECOM_AGENT_ID "AgentId (positive decimal):"
require_match "$WECOM_AGENT_ID" '^[1-9][0-9]{0,9}$' "AgentId has an invalid shape"
(( 10#$WECOM_AGENT_ID <= 4294967295 )) || fail "AgentId exceeds the unsigned 32-bit range"
step "Copy the enterprise member UserID that is allowed to run the two-message acceptance test."
ask WECOM_ALLOWED_USER_ID "Allowed test member UserID:"
require_match "$WECOM_ALLOWED_USER_ID" '^[A-Za-z0-9_.@-]{1,128}$' "test member UserID has an invalid shape"

stage "App and callback credentials"
say "Nothing entered here is printed or sent to GitHub. Values are saved only in the ignored local env file."
step "In the self-built app, reveal/copy Secret."
ask_secret TRPC_SECRET_WECOM_CORP_SECRET "App Secret (copy exactly):"
require_match "$TRPC_SECRET_WECOM_CORP_SECRET" '^[A-Za-z0-9_-]{16,128}$' "WeCom app Secret has an invalid shape"
step "In Receive Messages/API Reception, choose or copy the callback Token."
ask_secret TRPC_SECRET_WECOM_TOKEN "Callback Token (1-64 URL-safe characters):"
require_match "$TRPC_SECRET_WECOM_TOKEN" '^[A-Za-z0-9_-]{1,64}$' "WeCom callback Token has an invalid shape"
step "Choose or copy the 43-character EncodingAESKey."
ask_secret TRPC_SECRET_WECOM_AES "EncodingAESKey (43 characters):"
require_match "$TRPC_SECRET_WECOM_AES" '^[A-Za-z0-9+/]{43}$' "EncodingAESKey must be unpadded standard base64"

stage "Public HTTPS callback"
say "Prepare a public HTTPS tunnel or test ingress that forwards to local Gateway port 8080."
step "Enter only the public base URL. The path must be /webhook and it must not contain a query string."
ask WECOM_CALLBACK_BASE_URL "Callback base URL (https://host/webhook):"
require_match "$WECOM_CALLBACK_BASE_URL" '^https://[^/?#]+(:[0-9]{1,5})?/webhook$' "callback base URL must be public HTTPS with the exact /webhook path"
ask_secret TRPC_WEBHOOK_ROUTE_KEY "Opaque route key (Enter generates/keeps a local one):"
if [[ -z "$TRPC_WEBHOOK_ROUTE_KEY" ]]; then
  TRPC_WEBHOOK_ROUTE_KEY=$(random_urlsafe)
fi
require_match "$TRPC_WEBHOOK_ROUTE_KEY" '^[A-Za-z0-9_-]{32,128}$' "route key must be 32-128 URL-safe characters"

stage "Local runtime secrets"
say "The wizard also prepares fresh local-only platform keys needed by the Compose sandbox."
ensure_secret POSTGRES_PASSWORD
ensure_secret MASTER_KEY
ensure_secret SERVICE_AUTH_SECRET
ensure_secret ADMIN_API_TOKEN
ensure_secret AUDIT_IDENTITY_HMAC_KEY
ensure_secret GRAFANA_PASSWORD
ask_secret TRPC_SECRET_OPENAI_API_KEY "OpenAI-compatible provider key (optional; leave blank for URL verification only):"

for pair in \
  "POSTGRES_PASSWORD:$POSTGRES_PASSWORD" \
  "MASTER_KEY:$MASTER_KEY" \
  "SERVICE_AUTH_SECRET:$SERVICE_AUTH_SECRET" \
  "ADMIN_API_TOKEN:$ADMIN_API_TOKEN" \
  "AUDIT_IDENTITY_HMAC_KEY:$AUDIT_IDENTITY_HMAC_KEY" \
  "GRAFANA_PASSWORD:$GRAFANA_PASSWORD" \
  "POSTGRES_HOST_PORT:15432" \
  "OTEL_GRPC_HOST_PORT:14317" \
  "OTEL_HTTP_HOST_PORT:14318" \
  "GATEWAY_HOST_PORT:18080" \
  "ADMIN_HOST_PORT:18081" \
  "PROMETHEUS_HOST_PORT:19095" \
  "GRAFANA_HOST_PORT:13000" \
  "TRPC_WEBHOOK_ROUTE_KEY:$TRPC_WEBHOOK_ROUTE_KEY" \
  "TRPC_SECRET_WECOM_TOKEN:$TRPC_SECRET_WECOM_TOKEN" \
  "TRPC_SECRET_WECOM_CORP_SECRET:$TRPC_SECRET_WECOM_CORP_SECRET" \
  "TRPC_SECRET_WECOM_AES:$TRPC_SECRET_WECOM_AES" \
  "WECOM_CORP_ID:$WECOM_CORP_ID" \
  "WECOM_AGENT_ID:$WECOM_AGENT_ID" \
  "WECOM_ALLOWED_USER_ID:$WECOM_ALLOWED_USER_ID" \
  "WECOM_CALLBACK_BASE_URL:$WECOM_CALLBACK_BASE_URL"; do
  write_env "${pair%%:*}" "${pair#*:}"
done
if [[ -n "$TRPC_SECRET_OPENAI_API_KEY" ]]; then
  write_env TRPC_SECRET_OPENAI_API_KEY "$TRPC_SECRET_OPENAI_API_KEY"
fi
chmod 600 "$ENV_FILE" 2>/dev/null || true

stage "Zero-call preflight and console save"
say "First run the zero-provider-call preflight. It validates shapes, DNS and TLS without revealing values."
if command -v powershell.exe >/dev/null 2>&1; then
  export TRPC_WEBHOOK_ROUTE_KEY TRPC_SECRET_WECOM_TOKEN TRPC_SECRET_WECOM_CORP_SECRET TRPC_SECRET_WECOM_AES
  export WECOM_CORP_ID WECOM_AGENT_ID
  if powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts/external_acceptance_preflight.ps1 \
      -Channel WeCom -CallbackBaseUrl "$WECOM_CALLBACK_BASE_URL"; then
    note "zero-call credential and URL preflight passed; bootstrap performs the strict endpoint probe"
  else
    fail "zero-call preflight failed; do not spend a WeCom console-save attempt yet"
  fi
else
  SKIPPED+=("zero-call PowerShell preflight")
  warn "powershell.exe is unavailable; run scripts/external_acceptance_preflight.ps1 manually"
fi
step "Start/bootstrap the sandbox using the documented command, then return to the WeCom callback page."
step "Build the callback URL as: base URL + ?token= + the route key stored in the local env file."
if command -v clip.exe >/dev/null 2>&1 && confirm "Copy the full secret-bearing callback URL to the Windows clipboard now?"; then
  printf '%s' "${WECOM_CALLBACK_BASE_URL}?token=${TRPC_WEBHOOK_ROUTE_KEY}" | clip.exe
  note "callback URL copied; paste it only into the WeCom console and clear the clipboard afterward"
else
  SKIPPED+=("copy callback URL from WECOM_CALLBACK_BASE_URL and TRPC_WEBHOOK_ROUTE_KEY")
fi
step "Paste the callback URL, Token and EncodingAESKey in the WeCom console only after Gateway is reachable, then click Save once."
warn "Do not click Save before the local preflight and Gateway health checks pass."

finish
